name: flex-automation-cronjob

on:
  schedule:
    - cron: '35 11 * * *'

jobs:

  cronjob_to_run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Tests
      run: |  
          mvn clean 
          mvn clean install    
